# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_device_journeys200_response_journeys_inner import (
    GetDeviceJourneys200ResponseJourneysInner,
)


class TestGetDeviceJourneys200ResponseJourneysInner(unittest.TestCase):
    """GetDeviceJourneys200ResponseJourneysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetDeviceJourneys200ResponseJourneysInner:
        """Test GetDeviceJourneys200ResponseJourneysInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetDeviceJourneys200ResponseJourneysInner`
        """
        model = GetDeviceJourneys200ResponseJourneysInner()
        if include_optional:
            return GetDeviceJourneys200ResponseJourneysInner(
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                journey_id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_events = 56
            )
        else:
            return GetDeviceJourneys200ResponseJourneysInner(
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                journey_id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_events = 56,
        )
        """

    def testGetDeviceJourneys200ResponseJourneysInner(self):
        """Test GetDeviceJourneys200ResponseJourneysInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
