# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_billing_account_balance_history200_response import (
    GetBillingAccountBalanceHistory200Response,
)


class TestGetBillingAccountBalanceHistory200Response(unittest.TestCase):
    """GetBillingAccountBalanceHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetBillingAccountBalanceHistory200Response:
        """Test GetBillingAccountBalanceHistory200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetBillingAccountBalanceHistory200Response`
        """
        model = GetBillingAccountBalanceHistory200Response()
        if include_optional:
            return GetBillingAccountBalanceHistory200Response(
                data = [
                    notehub_py.models.get_billing_account_balance_history_200_response_data_inner.GetBillingAccountBalanceHistory_200_response_data_inner(
                        period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        remaining_event_capacity = 56, 
                        total_event_capacity_used = 56, )
                    ]
            )
        else:
            return GetBillingAccountBalanceHistory200Response(
        )
        """

    def testGetBillingAccountBalanceHistory200Response(self):
        """Test GetBillingAccountBalanceHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
