# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_device_journeys200_response import (
    GetDeviceJourneys200Response,
)


class TestGetDeviceJourneys200Response(unittest.TestCase):
    """GetDeviceJourneys200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDeviceJourneys200Response:
        """Test GetDeviceJourneys200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetDeviceJourneys200Response`
        """
        model = GetDeviceJourneys200Response()
        if include_optional:
            return GetDeviceJourneys200Response(
                has_more = True,
                journeys = [
                    notehub_py.models.get_device_journeys_200_response_journeys_inner.GetDeviceJourneys_200_response_journeys_inner(
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        journey_id = 56, 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_events = 56, )
                    ]
            )
        else:
            return GetDeviceJourneys200Response(
                has_more = True,
                journeys = [
                    notehub_py.models.get_device_journeys_200_response_journeys_inner.GetDeviceJourneys_200_response_journeys_inner(
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        journey_id = 56, 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_events = 56, )
                    ],
        )
        """

    def testGetDeviceJourneys200Response(self):
        """Test GetDeviceJourneys200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
