# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.job_definition_report_options import JobDefinitionReportOptions


class TestJobDefinitionReportOptions(unittest.TestCase):
    """JobDefinitionReportOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobDefinitionReportOptions:
        """Test JobDefinitionReportOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobDefinitionReportOptions`
        """
        model = JobDefinitionReportOptions()
        if include_optional:
            return JobDefinitionReportOptions(
                app_fleets = True,
                app_info = True,
                app_vars = True,
                comment = '',
                device_activity = True,
                device_health = True,
                device_info = True,
                device_vars = True
            )
        else:
            return JobDefinitionReportOptions(
        )
        """

    def testJobDefinitionReportOptions(self):
        """Test JobDefinitionReportOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
