# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.batch_job_note_request import BatchJobNoteRequest


class TestBatchJobNoteRequest(unittest.TestCase):
    """BatchJobNoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchJobNoteRequest:
        """Test BatchJobNoteRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BatchJobNoteRequest`
        """
        model = BatchJobNoteRequest()
        if include_optional:
            return BatchJobNoteRequest(
                body = { },
                file = '',
                note = '',
                req = 'note.add'
            )
        else:
            return BatchJobNoteRequest(
                file = '',
                req = 'note.add',
        )
        """

    def testBatchJobNoteRequest(self):
        """Test BatchJobNoteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
