# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.job_detail import JobDetail


class TestJobDetail(unittest.TestCase):
    """JobDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobDetail:
        """Test JobDetail
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobDetail`
        """
        model = JobDetail()
        if include_optional:
            return JobDetail(
                created = 56,
                created_by = '',
                job_uid = '',
                last_run_completed = 1775252922,
                last_run_status = 'dry run completed successfully',
                last_run_submitted = 1775252900,
                name = '',
                definition = {"comment":"Set environment variables on all devices in a fleet","default_requests":{"vars_to_set":{"firmware_channel":"production","log_level":"1"}},"select":{"devices_in_fleets":["fleet:00000000-0000-0000-0000-000000000000"]}}
            )
        else:
            return JobDetail(
                created = 56,
                created_by = '',
                job_uid = '',
                name = '',
        )
        """

    def testJobDetail(self):
        """Test JobDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
