# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_project_secrets_response import GetProjectSecretsResponse


class TestGetProjectSecretsResponse(unittest.TestCase):
    """GetProjectSecretsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectSecretsResponse:
        """Test GetProjectSecretsResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetProjectSecretsResponse`
        """
        model = GetProjectSecretsResponse()
        if include_optional:
            return GetProjectSecretsResponse(
                secrets = [
                    notehub_py.models.project_secret.ProjectSecret(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        modified_by = '', 
                        name = '', )
                    ]
            )
        else:
            return GetProjectSecretsResponse(
                secrets = [
                    notehub_py.models.project_secret.ProjectSecret(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        modified_by = '', 
                        name = '', )
                    ],
        )
        """

    def testGetProjectSecretsResponse(self):
        """Test GetProjectSecretsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
