# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.job_run import JobRun


class TestJobRun(unittest.TestCase):
    """JobRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobRun:
        """Test JobRun
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobRun`
        """
        model = JobRun()
        if include_optional:
            return JobRun(
                cancel = True,
                completed = 56,
                dry_run = True,
                job_name = '',
                job_uid = '',
                report_uid = '',
                results = { },
                started = 56,
                status = '',
                submitted = 56,
                submitted_by = '',
                updated = 56
            )
        else:
            return JobRun(
                dry_run = True,
                job_name = '',
                job_uid = '',
                report_uid = '',
                status = '',
                submitted = 56,
                submitted_by = '',
                updated = 56,
        )
        """

    def testJobRun(self):
        """Test JobRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
