# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_job_run(self) -> None:
        """Test case for cancel_job_run"""
        pass

    def test_create_job(self) -> None:
        """Test case for create_job"""
        pass

    def test_delete_job(self) -> None:
        """Test case for delete_job"""
        pass

    def test_get_job(self) -> None:
        """Test case for get_job"""
        pass

    def test_get_job_run(self) -> None:
        """Test case for get_job_run"""
        pass

    def test_get_job_runs(self) -> None:
        """Test case for get_job_runs"""
        pass

    def test_get_jobs(self) -> None:
        """Test case for get_jobs"""
        pass

    def test_run_job(self) -> None:
        """Test case for run_job"""
        pass


if __name__ == "__main__":
    unittest.main()
