# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.api.description_api import DescriptionApi


class TestDescriptionApi(unittest.TestCase):
    """DescriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DescriptionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_global_description(self) -> None:
        """Test case for delete_global_description"""
        pass

    def test_delete_project_description(self) -> None:
        """Test case for delete_project_description"""
        pass

    def test_get_global_description(self) -> None:
        """Test case for get_global_description"""
        pass

    def test_get_project_description(self) -> None:
        """Test case for get_project_description"""
        pass

    def test_list_global_descriptions(self) -> None:
        """Test case for list_global_descriptions"""
        pass

    def test_list_project_descriptions(self) -> None:
        """Test case for list_project_descriptions"""
        pass

    def test_set_global_description(self) -> None:
        """Test case for set_global_description"""
        pass

    def test_set_project_description(self) -> None:
        """Test case for set_project_description"""
        pass


if __name__ == "__main__":
    unittest.main()
