# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.description_record_list import DescriptionRecordList


class TestDescriptionRecordList(unittest.TestCase):
    """DescriptionRecordList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DescriptionRecordList:
        """Test DescriptionRecordList
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DescriptionRecordList`
        """
        model = DescriptionRecordList()
        if include_optional:
            return DescriptionRecordList(
                descriptions = [
                    notehub_py.models.description_record.DescriptionRecord(
                        content_type = '', 
                        created_at = 56, 
                        created_by = '', 
                        length = 56, 
                        md5 = '', 
                        modified_at = 56, 
                        modified_by = '', 
                        name = '', 
                        owner_uid = '', 
                        scope = '', )
                    ]
            )
        else:
            return DescriptionRecordList(
                descriptions = [
                    notehub_py.models.description_record.DescriptionRecord(
                        content_type = '', 
                        created_at = 56, 
                        created_by = '', 
                        length = 56, 
                        md5 = '', 
                        modified_at = 56, 
                        modified_by = '', 
                        name = '', 
                        owner_uid = '', 
                        scope = '', )
                    ],
        )
        """

    def testDescriptionRecordList(self):
        """Test DescriptionRecordList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
