# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.batch_job_requests import BatchJobRequests


class TestBatchJobRequests(unittest.TestCase):
    """BatchJobRequests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchJobRequests:
        """Test BatchJobRequests
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BatchJobRequests`
        """
        model = BatchJobRequests()
        if include_optional:
            return BatchJobRequests(
                comment = '',
                connectivity_assurance_disable = True,
                connectivity_assurance_enable = True,
                disable = True,
                enable = True,
                fleets_to_default = [
                    ''
                    ],
                fleets_to_join = [
                    ''
                    ],
                fleets_to_leave = [
                    ''
                    ],
                provision_product = '',
                sn_to_default = '',
                sn_to_set = '',
                vars_to_default = {
                    'key' : ''
                    },
                vars_to_set = {
                    'key' : ''
                    }
            )
        else:
            return BatchJobRequests(
        )
        """

    def testBatchJobRequests(self):
        """Test BatchJobRequests"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
