# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_get_organization(self) -> None:
        """Test case for get_organization"""
        pass

    def test_get_organization_balance_history(self) -> None:
        """Test case for get_organization_balance_history"""
        pass

    def test_get_organizations(self) -> None:
        """Test case for get_organizations"""
        pass


if __name__ == "__main__":
    unittest.main()
