# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.job_definition import JobDefinition


class TestJobDefinition(unittest.TestCase):
    """JobDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobDefinition:
        """Test JobDefinition
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobDefinition`
        """
        model = JobDefinition()
        if include_optional:
            return JobDefinition(
                comment = '',
                default_requests = notehub_py.models.batch_job_requests.BatchJobRequests(
                    comment = '', 
                    connectivity_assurance_disable = True, 
                    connectivity_assurance_enable = True, 
                    disable = True, 
                    enable = True, 
                    fleets_to_default = [
                        ''
                        ], 
                    fleets_to_join = [
                        ''
                        ], 
                    fleets_to_leave = [
                        ''
                        ], 
                    provision_product = '', 
                    sn_to_default = '', 
                    sn_to_set = '', 
                    vars_to_default = {
                        'key' : ''
                        }, 
                    vars_to_set = {
                        'key' : ''
                        }, ),
                device_requests = {
                    'key' : notehub_py.models.batch_job_requests.BatchJobRequests(
                        comment = '', 
                        connectivity_assurance_disable = True, 
                        connectivity_assurance_enable = True, 
                        disable = True, 
                        enable = True, 
                        fleets_to_default = [
                            ''
                            ], 
                        fleets_to_join = [
                            ''
                            ], 
                        fleets_to_leave = [
                            ''
                            ], 
                        provision_product = '', 
                        sn_to_default = '', 
                        sn_to_set = '', 
                        vars_to_default = {
                            'key' : ''
                            }, 
                        vars_to_set = {
                            'key' : ''
                            }, )
                    },
                report_options = notehub_py.models.job_definition_report_options.JobDefinition_report_options(
                    app_fleets = True, 
                    app_info = True, 
                    app_vars = True, 
                    comment = '', 
                    device_activity = True, 
                    device_health = True, 
                    device_info = True, 
                    device_vars = True, ),
                select = notehub_py.models.job_definition_select.JobDefinition_select(
                    all_devices = True, 
                    comment = '', 
                    devices = [
                        ''
                        ], 
                    devices_by_sn = [
                        ''
                        ], 
                    devices_in_fleets = [
                        ''
                        ], )
            )
        else:
            return JobDefinition(
        )
        """

    def testJobDefinition(self):
        """Test JobDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
