# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_billing_account200_response import (
    GetBillingAccount200Response,
)


class TestGetBillingAccount200Response(unittest.TestCase):
    """GetBillingAccount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingAccount200Response:
        """Test GetBillingAccount200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetBillingAccount200Response`
        """
        model = GetBillingAccount200Response()
        if include_optional:
            return GetBillingAccount200Response(
                name = '',
                owner = '',
                plan = notehub_py.models.get_billing_account_200_response_plan.GetBillingAccount_200_response_plan(
                    current_balance = 56, 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    event_capacity = 56, 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    type = 'Enterprise', ),
                suspended = True,
                uid = ''
            )
        else:
            return GetBillingAccount200Response(
        )
        """

    def testGetBillingAccount200Response(self):
        """Test GetBillingAccount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
