# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_jobs200_response import GetJobs200Response


class TestGetJobs200Response(unittest.TestCase):
    """GetJobs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJobs200Response:
        """Test GetJobs200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetJobs200Response`
        """
        model = GetJobs200Response()
        if include_optional:
            return GetJobs200Response(
                jobs = [
                    notehub_py.models.job.Job(
                        created = 56, 
                        created_by = '', 
                        definition = { }, 
                        job_uid = '', 
                        name = '', )
                    ]
            )
        else:
            return GetJobs200Response(
                jobs = [
                    notehub_py.models.job.Job(
                        created = 56, 
                        created_by = '', 
                        definition = { }, 
                        job_uid = '', 
                        name = '', )
                    ],
        )
        """

    def testGetJobs200Response(self):
        """Test GetJobs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
