# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.description_record import DescriptionRecord


class TestDescriptionRecord(unittest.TestCase):
    """DescriptionRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DescriptionRecord:
        """Test DescriptionRecord
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DescriptionRecord`
        """
        model = DescriptionRecord()
        if include_optional:
            return DescriptionRecord(
                content_type = '',
                created_at = 56,
                created_by = '',
                length = 56,
                md5 = '',
                modified_at = 56,
                modified_by = '',
                name = '',
                owner_uid = '',
                scope = ''
            )
        else:
            return DescriptionRecord(
                content_type = '',
                created_at = 56,
                length = 56,
                md5 = '',
                modified_at = 56,
                name = '',
                scope = '',
        )
        """

    def testDescriptionRecord(self):
        """Test DescriptionRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
