# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_billing_account_balance_history200_response_data_inner import (
    GetBillingAccountBalanceHistory200ResponseDataInner,
)


class TestGetBillingAccountBalanceHistory200ResponseDataInner(unittest.TestCase):
    """GetBillingAccountBalanceHistory200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetBillingAccountBalanceHistory200ResponseDataInner:
        """Test GetBillingAccountBalanceHistory200ResponseDataInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetBillingAccountBalanceHistory200ResponseDataInner`
        """
        model = GetBillingAccountBalanceHistory200ResponseDataInner()
        if include_optional:
            return GetBillingAccountBalanceHistory200ResponseDataInner(
                period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                remaining_event_capacity = 56,
                total_event_capacity_used = 56
            )
        else:
            return GetBillingAccountBalanceHistory200ResponseDataInner(
                period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                remaining_event_capacity = 56,
                total_event_capacity_used = 56,
        )
        """

    def testGetBillingAccountBalanceHistory200ResponseDataInner(self):
        """Test GetBillingAccountBalanceHistory200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
