# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.organization_role import OrganizationRole


class TestOrganizationRole(unittest.TestCase):
    """OrganizationRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationRole(self):
        """Test OrganizationRole"""
        # inst = OrganizationRole()


if __name__ == "__main__":
    unittest.main()
