# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_api_usage200_response import GetApiUsage200Response


class TestGetApiUsage200Response(unittest.TestCase):
    """GetApiUsage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiUsage200Response:
        """Test GetApiUsage200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetApiUsage200Response`
        """
        model = GetApiUsage200Response()
        if include_optional:
            return GetApiUsage200Response(
                data = [
                    notehub_py.models.usage_api_data.UsageApiData(
                        endpoint = '/v1/projects/{projectOrProductUID}/devices', 
                        method = 'GET', 
                        period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        requests = 1284, )
                    ],
                truncated = True
            )
        else:
            return GetApiUsage200Response(
                data = [
                    notehub_py.models.usage_api_data.UsageApiData(
                        endpoint = '/v1/projects/{projectOrProductUID}/devices', 
                        method = 'GET', 
                        period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        requests = 1284, )
                    ],
        )
        """

    def testGetApiUsage200Response(self):
        """Test GetApiUsage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
