# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class ArchiveStats(BaseModel):
    """
    Statistics about a repository's data archive.
    """  # noqa: E501

    begin: Optional[datetime] = Field(
        default=None, description="Timestamp of the earliest archived record."
    )
    end: Optional[datetime] = Field(
        default=None, description="Timestamp of the latest archived record."
    )
    file_count: Optional[StrictInt] = Field(
        default=None, description="Number of archive files."
    )
    record_count: Optional[StrictInt] = Field(
        default=None,
        description="Total number of records across all archive files. Null when the count cannot be determined because one or more archive files predate the record-count filename format.",
    )
    total_size_bytes: Optional[StrictInt] = Field(
        default=None, description="Total size of all archive files, in bytes."
    )
    __properties: ClassVar[List[str]] = [
        "begin",
        "end",
        "file_count",
        "record_count",
        "total_size_bytes",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArchiveStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if record_count (nullable) is None
        # and model_fields_set contains the field
        if self.record_count is None and "record_count" in self.model_fields_set:
            _dict["record_count"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArchiveStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "begin": obj.get("begin"),
                "end": obj.get("end"),
                "file_count": obj.get("file_count"),
                "record_count": obj.get("record_count"),
                "total_size_bytes": obj.get("total_size_bytes"),
            }
        )
        return _obj
