# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from notehub_py.models.batch_job_note_request import BatchJobNoteRequest
from typing import Optional, Set
from typing_extensions import Self


class BatchJobRequests(BaseModel):
    """
    Operations to apply to a device
    """  # noqa: E501

    comment: Optional[StrictStr] = None
    connectivity_assurance_disable: Optional[StrictBool] = Field(
        default=None, description="Disable connectivity assurance for the device"
    )
    connectivity_assurance_enable: Optional[StrictBool] = Field(
        default=None, description="Enable connectivity assurance for the device"
    )
    disable: Optional[StrictBool] = Field(
        default=None, description="Disable the device"
    )
    enable: Optional[StrictBool] = Field(default=None, description="Enable the device")
    fleets_to_default: Optional[List[StrictStr]] = Field(
        default=None,
        description="Fleet UIDs to assign to the device if it has no fleets",
    )
    fleets_to_join: Optional[List[StrictStr]] = Field(
        default=None, description="Fleet UIDs to add the device to"
    )
    fleets_to_leave: Optional[List[StrictStr]] = Field(
        default=None, description="Fleet UIDs to remove the device from"
    )
    note_reqs: Optional[List[BatchJobNoteRequest]] = Field(
        default=None,
        description="note.add/note.update/note.delete requests to perform against the device's own notefiles. When both default_requests and a device's device_requests specify note_reqs, they merge by identity (req, file, note): a device-specific entry with the same identity as a default entry replaces it; entries unique to either side (no collision) all still apply.",
    )
    provision_product: Optional[StrictStr] = Field(
        default=None,
        description="Product UID to provision the device with if not already provisioned",
    )
    sn_to_default: Optional[StrictStr] = Field(
        default=None, description="Set the device serial number only if not already set"
    )
    sn_to_set: Optional[StrictStr] = Field(
        default=None, description='Set the device serial number ("-" to clear)'
    )
    vars_to_default: Optional[Dict[str, StrictStr]] = Field(
        default=None, description="Environment variables to set only if not already set"
    )
    vars_to_set: Optional[Dict[str, StrictStr]] = Field(
        default=None,
        description='Environment variables to set (use "-" as value to clear)',
    )
    __properties: ClassVar[List[str]] = [
        "comment",
        "connectivity_assurance_disable",
        "connectivity_assurance_enable",
        "disable",
        "enable",
        "fleets_to_default",
        "fleets_to_join",
        "fleets_to_leave",
        "note_reqs",
        "provision_product",
        "sn_to_default",
        "sn_to_set",
        "vars_to_default",
        "vars_to_set",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchJobRequests from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in note_reqs (list)
        _items = []
        if self.note_reqs:
            for _item in self.note_reqs:
                if _item:
                    _items.append(_item.to_dict())
            _dict["note_reqs"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchJobRequests from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "comment": obj.get("comment"),
                "connectivity_assurance_disable": obj.get(
                    "connectivity_assurance_disable"
                ),
                "connectivity_assurance_enable": obj.get(
                    "connectivity_assurance_enable"
                ),
                "disable": obj.get("disable"),
                "enable": obj.get("enable"),
                "fleets_to_default": obj.get("fleets_to_default"),
                "fleets_to_join": obj.get("fleets_to_join"),
                "fleets_to_leave": obj.get("fleets_to_leave"),
                "note_reqs": (
                    [BatchJobNoteRequest.from_dict(_item) for _item in obj["note_reqs"]]
                    if obj.get("note_reqs") is not None
                    else None
                ),
                "provision_product": obj.get("provision_product"),
                "sn_to_default": obj.get("sn_to_default"),
                "sn_to_set": obj.get("sn_to_set"),
                "vars_to_default": obj.get("vars_to_default"),
                "vars_to_set": obj.get("vars_to_set"),
            }
        )
        return _obj
