# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from notehub_py.models.data_set_field import DataSetField
from notehub_py.models.dataset_reload_progress import DatasetReloadProgress
from typing import Optional, Set
from typing_extensions import Self


class DataSet(BaseModel):
    """
    DataSet
    """  # noqa: E501

    fields: Optional[List[DataSetField]] = None
    is_optimized: Optional[StrictBool] = Field(
        default=None,
        description="True once the dataset's underlying table has been deduplicated/optimized. Server-populated; ignored on input.",
    )
    is_ready: Optional[StrictBool] = Field(
        default=None,
        description="True once the dataset has been fully loaded from the repository's archive after backfill completed. Server-populated; ignored on input.",
    )
    lat: Optional[StrictStr] = Field(
        default=None, description="JSONata expression resulting in the latitude field"
    )
    lon: Optional[StrictStr] = Field(
        default=None, description="JSONata expression resulting in the Longitude field"
    )
    name: Optional[StrictStr] = Field(
        default=None, description="The name of the data set"
    )
    notefiles: Optional[List[StrictStr]] = Field(
        default=None,
        description="If non-empty, only events from these notefiles populate the dataset. Empty or omitted means all notefiles.",
    )
    reload: Optional[DatasetReloadProgress] = None
    rows: Optional[StrictStr] = Field(
        default=None,
        description="Optional JSONata expression that expands one event into several rows. It evaluates to one row object per row, whose keys are the dataset's columns: an array of objects, or a single object for one row. Both are accepted because JSONata collapses a one-element sequence to the element, so the same expression yields an array for an event carrying several readings and a bare object for one carrying a single reading. A result that is undefined or empty contributes no rows and is not an error; anything that is not an object, or an array containing one, is rejected. When set it is the only expression that reads the event: each field below takes the row object key matching its name, and time/lat/lon name a key too. Omit it and the dataset produces one row per event, with each field's own jsonata expression reading the event directly. event.uploaded and event.captured always resolve against the event either way.",
    )
    time: Optional[StrictStr] = Field(
        default=None,
        description="JSONata expression resulting in the row's time. Required for a dataset with no rows expression. With one it defaults to the row object's \"time\" key, and only needs setting to name a different key, or to reach past the row as event.uploaded and event.captured do. lat and lon work the same way and are what declare that the dataset has a location column at all.",
    )
    __properties: ClassVar[List[str]] = [
        "fields",
        "is_optimized",
        "is_ready",
        "lat",
        "lon",
        "name",
        "notefiles",
        "reload",
        "rows",
        "time",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "is_optimized",
                "is_ready",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item in self.fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict["fields"] = _items
        # override the default output from pydantic by calling `to_dict()` of reload
        if self.reload:
            _dict["reload"] = self.reload.to_dict()
        # set to None if reload (nullable) is None
        # and model_fields_set contains the field
        if self.reload is None and "reload" in self.model_fields_set:
            _dict["reload"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "fields": (
                    [DataSetField.from_dict(_item) for _item in obj["fields"]]
                    if obj.get("fields") is not None
                    else None
                ),
                "is_optimized": obj.get("is_optimized"),
                "is_ready": obj.get("is_ready"),
                "lat": obj.get("lat"),
                "lon": obj.get("lon"),
                "name": obj.get("name"),
                "notefiles": obj.get("notefiles"),
                "reload": (
                    DatasetReloadProgress.from_dict(obj["reload"])
                    if obj.get("reload") is not None
                    else None
                ),
                "rows": obj.get("rows"),
                "time": obj.get("time"),
            }
        )
        return _obj
