# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class DescriptionRecord(BaseModel):
    """
    Metadata for a stored description record. The content itself is returned by GET on the record.
    """  # noqa: E501

    content_type: StrictStr = Field(
        description='The stored content type, either "application/json" or "text/plain; charset=utf-8".'
    )
    created_at: StrictInt = Field(
        description="When the record was first created (Unix seconds)."
    )
    created_by: Optional[StrictStr] = Field(
        default=None, description="The actor who created the record."
    )
    length: StrictInt = Field(description="The content length in bytes.")
    md5: StrictStr = Field(description="The hex-encoded MD5 of the content.")
    modified_at: StrictInt = Field(
        description="When the record was last updated (Unix seconds)."
    )
    modified_by: Optional[StrictStr] = Field(
        default=None, description="The actor who last updated the record."
    )
    name: StrictStr = Field(
        description="The record name (letters, digits, '.', '_' or '-')."
    )
    owner_uid: Optional[StrictStr] = Field(
        default=None,
        description="The owning project (app) UID for project-scoped records; empty for global.",
    )
    scope: StrictStr = Field(
        description='The ownership scope of the record ("global" or "project").'
    )
    __properties: ClassVar[List[str]] = [
        "content_type",
        "created_at",
        "created_by",
        "length",
        "md5",
        "modified_at",
        "modified_by",
        "name",
        "owner_uid",
        "scope",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DescriptionRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DescriptionRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "content_type": obj.get("content_type"),
                "created_at": obj.get("created_at"),
                "created_by": obj.get("created_by"),
                "length": obj.get("length"),
                "md5": obj.get("md5"),
                "modified_at": obj.get("modified_at"),
                "modified_by": obj.get("modified_by"),
                "name": obj.get("name"),
                "owner_uid": obj.get("owner_uid"),
                "scope": obj.get("scope"),
            }
        )
        return _obj
