# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from notehub_py.models.get_device_journey200_response_journey import (
    GetDeviceJourney200ResponseJourney,
)
from typing import Optional, Set
from typing_extensions import Self


class GetDeviceJourney200Response(BaseModel):
    """
    GetDeviceJourney200Response
    """  # noqa: E501

    end_date: datetime = Field(description="Latest event time within the journey.")
    journey: GetDeviceJourney200ResponseJourney
    journey_id: StrictInt = Field(description="Identifier of the journey.")
    start_date: datetime = Field(description="Earliest event time within the journey.")
    __properties: ClassVar[List[str]] = [
        "end_date",
        "journey",
        "journey_id",
        "start_date",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDeviceJourney200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of journey
        if self.journey:
            _dict["journey"] = self.journey.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDeviceJourney200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "end_date": obj.get("end_date"),
                "journey": (
                    GetDeviceJourney200ResponseJourney.from_dict(obj["journey"])
                    if obj.get("journey") is not None
                    else None
                ),
                "journey_id": obj.get("journey_id"),
                "start_date": obj.get("start_date"),
            }
        )
        return _obj
