# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from notehub_py.models.job_definition import JobDefinition
from typing import Optional, Set
from typing_extensions import Self


class JobDetail(BaseModel):
    """
    Batch job with full definition
    """  # noqa: E501

    created: StrictInt = Field(description="Unix timestamp when job was created")
    created_by: StrictStr = Field(description="User who created the job")
    job_uid: StrictStr = Field(description="Unique identifier for the job")
    last_run_completed: Optional[StrictInt] = Field(
        default=None,
        description="Unix timestamp when the most recent run completed (0 if still in progress)",
    )
    last_run_status: Optional[StrictStr] = Field(
        default=None,
        description='Status of the most recent job run. Terminal values are: "submitted", "completed successfully", "dry run completed successfully", "completed with errors", "cancelled". While a job is running, intermediate per-device progress updates may appear (e.g. "dev:000000000000000 completed", "dev:000000000000000 updated: ...").',
    )
    last_run_submitted: Optional[StrictInt] = Field(
        default=None,
        description="Unix timestamp when the most recent run was submitted",
    )
    name: StrictStr = Field(description="Human-readable job name")
    definition: Optional[JobDefinition] = None
    __properties: ClassVar[List[str]] = [
        "created",
        "created_by",
        "job_uid",
        "last_run_completed",
        "last_run_status",
        "last_run_submitted",
        "name",
        "definition",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of definition
        if self.definition:
            _dict["definition"] = self.definition.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "created": obj.get("created"),
                "created_by": obj.get("created_by"),
                "job_uid": obj.get("job_uid"),
                "last_run_completed": obj.get("last_run_completed"),
                "last_run_status": obj.get("last_run_status"),
                "last_run_submitted": obj.get("last_run_submitted"),
                "name": obj.get("name"),
                "definition": (
                    JobDefinition.from_dict(obj["definition"])
                    if obj.get("definition") is not None
                    else None
                ),
            }
        )
        return _obj
