# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from notehub_py.models.batch_job_requests import BatchJobRequests
from notehub_py.models.job_definition_report_options import JobDefinitionReportOptions
from notehub_py.models.job_definition_select import JobDefinitionSelect
from typing import Optional, Set
from typing_extensions import Self


class JobDefinition(BaseModel):
    """
    Batch job definition
    """  # noqa: E501

    comment: Optional[StrictStr] = Field(
        default=None, description="Human-readable description of the job"
    )
    default_requests: Optional[BatchJobRequests] = None
    device_requests: Optional[Dict[str, BatchJobRequests]] = Field(
        default=None,
        description="Device-specific request overrides, keyed by device UID",
    )
    report_options: Optional[JobDefinitionReportOptions] = None
    select: Optional[JobDefinitionSelect] = None
    __properties: ClassVar[List[str]] = [
        "comment",
        "default_requests",
        "device_requests",
        "report_options",
        "select",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_requests
        if self.default_requests:
            _dict["default_requests"] = self.default_requests.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in device_requests (dict)
        _field_dict = {}
        if self.device_requests:
            for _key in self.device_requests:
                if self.device_requests[_key]:
                    _field_dict[_key] = self.device_requests[_key].to_dict()
            _dict["device_requests"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of report_options
        if self.report_options:
            _dict["report_options"] = self.report_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of select
        if self.select:
            _dict["select"] = self.select.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "comment": obj.get("comment"),
                "default_requests": (
                    BatchJobRequests.from_dict(obj["default_requests"])
                    if obj.get("default_requests") is not None
                    else None
                ),
                "device_requests": (
                    dict(
                        (_k, BatchJobRequests.from_dict(_v))
                        for _k, _v in obj["device_requests"].items()
                    )
                    if obj.get("device_requests") is not None
                    else None
                ),
                "report_options": (
                    JobDefinitionReportOptions.from_dict(obj["report_options"])
                    if obj.get("report_options") is not None
                    else None
                ),
                "select": (
                    JobDefinitionSelect.from_dict(obj["select"])
                    if obj.get("select") is not None
                    else None
                ),
            }
        )
        return _obj
