# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class JobDefinitionSelect(BaseModel):
    """
    Device selection criteria
    """  # noqa: E501

    all_devices: Optional[StrictBool] = Field(
        default=None, description="Select all devices in the project"
    )
    comment: Optional[StrictStr] = None
    devices: Optional[List[StrictStr]] = Field(
        default=None, description="Specific device UIDs to include"
    )
    devices_by_sn: Optional[List[StrictStr]] = Field(
        default=None,
        description="Serial number patterns to match (supports glob wildcards *, ?, [...])",
    )
    devices_in_fleets: Optional[List[StrictStr]] = Field(
        default=None, description="Fleet UIDs whose devices should be included"
    )
    __properties: ClassVar[List[str]] = [
        "all_devices",
        "comment",
        "devices",
        "devices_by_sn",
        "devices_in_fleets",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobDefinitionSelect from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobDefinitionSelect from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "all_devices": obj.get("all_devices"),
                "comment": obj.get("comment"),
                "devices": obj.get("devices"),
                "devices_by_sn": obj.get("devices_by_sn"),
                "devices_in_fleets": obj.get("devices_in_fleets"),
            }
        )
        return _obj
