# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class JobRun(BaseModel):
    """
    JobRun
    """  # noqa: E501

    cancel: Optional[StrictBool] = Field(
        default=None, description="Whether cancellation was requested"
    )
    completed: Optional[StrictInt] = Field(
        default=None, description="Unix timestamp when completed"
    )
    dry_run: StrictBool = Field(description="Whether this was a dry run")
    job_name: StrictStr = Field(description="Name of the job")
    job_uid: StrictStr = Field(description="Unique identifier for the job")
    report_uid: StrictStr = Field(description="Unique identifier for this run")
    results: Optional[Dict[str, Any]] = Field(
        default=None, description="Full results (only in detail view)"
    )
    started: Optional[StrictInt] = Field(
        default=None, description="Unix timestamp when started"
    )
    status: StrictStr = Field(
        description="Current status (submitted, running, completed, cancelled, failed)"
    )
    submitted: StrictInt = Field(description="Unix timestamp when submitted")
    submitted_by: StrictStr = Field(description="User who submitted the run")
    updated: StrictInt = Field(description="Unix timestamp of last update")
    __properties: ClassVar[List[str]] = [
        "cancel",
        "completed",
        "dry_run",
        "job_name",
        "job_uid",
        "report_uid",
        "results",
        "started",
        "status",
        "submitted",
        "submitted_by",
        "updated",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "cancel": obj.get("cancel"),
                "completed": obj.get("completed"),
                "dry_run": obj.get("dry_run"),
                "job_name": obj.get("job_name"),
                "job_uid": obj.get("job_uid"),
                "report_uid": obj.get("report_uid"),
                "results": obj.get("results"),
                "started": obj.get("started"),
                "status": obj.get("status"),
                "submitted": obj.get("submitted"),
                "submitted_by": obj.get("submitted_by"),
                "updated": obj.get("updated"),
            }
        )
        return _obj
