# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class RepositoryTokenRequest(BaseModel):
    """
    RepositoryTokenRequest
    """  # noqa: E501

    intent: Optional[StrictStr] = Field(
        default="read",
        description="Access intent for the vended credentials. Only `read` is supported today; `write` and `admin` are reserved for future use. ",
    )
    ttl_seconds: Optional[Annotated[int, Field(le=3600, strict=True, ge=60)]] = Field(
        default=900,
        description="Requested credential lifetime in seconds. Clamped server-side to [60, 3600]. Defaults to 900 (15 minutes) if omitted. ",
    )
    __properties: ClassVar[List[str]] = ["intent", "ttl_seconds"]

    @field_validator("intent")
    def intent_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["read"]):
            raise ValueError("must be one of enum values ('read')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RepositoryTokenRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RepositoryTokenRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "intent": (
                    obj.get("intent") if obj.get("intent") is not None else "read"
                ),
                "ttl_seconds": (
                    obj.get("ttl_seconds")
                    if obj.get("ttl_seconds") is not None
                    else 900
                ),
            }
        )
        return _obj
