# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from notehub_py.models.archive_stats import ArchiveStats
from typing import Optional, Set
from typing_extensions import Self


class Repository(BaseModel):
    """
    Repository
    """  # noqa: E501

    archive: Optional[ArchiveStats] = None
    fleet_uids: Optional[List[StrictStr]] = None
    name: Optional[StrictStr] = Field(default=None, description="repository name")
    project_uids: Optional[List[StrictStr]] = None
    uid: Optional[StrictStr] = Field(
        default=None, description="The unique identifier for the data repository"
    )
    __properties: ClassVar[List[str]] = [
        "archive",
        "fleet_uids",
        "name",
        "project_uids",
        "uid",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Repository from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of archive
        if self.archive:
            _dict["archive"] = self.archive.to_dict()
        # set to None if archive (nullable) is None
        # and model_fields_set contains the field
        if self.archive is None and "archive" in self.model_fields_set:
            _dict["archive"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Repository from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "archive": (
                    ArchiveStats.from_dict(obj["archive"])
                    if obj.get("archive") is not None
                    else None
                ),
                "fleet_uids": obj.get("fleet_uids"),
                "name": obj.get("name"),
                "project_uids": obj.get("project_uids"),
                "uid": obj.get("uid"),
            }
        )
        return _obj
