# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class UsageData(BaseModel):
    """
    UsageData
    """  # noqa: E501

    billable_bytes_total: Optional[StrictInt] = Field(
        default=None,
        description="Total billable bytes (only for packet-based protocols)",
    )
    downlink_bytes: Optional[StrictInt] = None
    downlink_bytes_billable: Optional[StrictInt] = Field(
        default=None,
        description="Billable downlink bytes (only for packet-based protocols)",
    )
    downlink_packets: Optional[StrictInt] = Field(
        default=None, description="Downlink packets (only for packet-based protocols)"
    )
    period: datetime
    total_bytes: StrictInt
    uplink_bytes: Optional[StrictInt] = None
    uplink_bytes_billable: Optional[StrictInt] = Field(
        default=None,
        description="Billable uplink bytes (only for packet-based protocols)",
    )
    uplink_packets: Optional[StrictInt] = Field(
        default=None, description="Uplink packets (only for packet-based protocols)"
    )
    __properties: ClassVar[List[str]] = [
        "billable_bytes_total",
        "downlink_bytes",
        "downlink_bytes_billable",
        "downlink_packets",
        "period",
        "total_bytes",
        "uplink_bytes",
        "uplink_bytes_billable",
        "uplink_packets",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "billable_bytes_total": obj.get("billable_bytes_total"),
                "downlink_bytes": obj.get("downlink_bytes"),
                "downlink_bytes_billable": obj.get("downlink_bytes_billable"),
                "downlink_packets": obj.get("downlink_packets"),
                "period": obj.get("period"),
                "total_bytes": obj.get("total_bytes"),
                "uplink_bytes": obj.get("uplink_bytes"),
                "uplink_bytes_billable": obj.get("uplink_bytes_billable"),
                "uplink_packets": obj.get("uplink_packets"),
            }
        )
        return _obj
