# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class UsageSessionsData(BaseModel):
    """
    UsageSessionsData
    """  # noqa: E501

    device: Optional[StrictStr] = None
    first_sync_sessions: StrictInt = Field(
        description="Number of first sync sessions in this period"
    )
    fleet: Optional[StrictStr] = None
    period: datetime
    sessions: StrictInt
    sessions_by_transport: Optional[Dict[str, StrictInt]] = Field(
        default=None,
        description="Count of sessions grouped by transport type prefix (e.g. cell, wifi, ntn, lorawan)",
    )
    tls_sessions: Optional[StrictInt] = Field(
        default=None, description="Number of TLS sessions in this period"
    )
    total_bytes: StrictInt
    total_devices: StrictInt
    __properties: ClassVar[List[str]] = [
        "device",
        "first_sync_sessions",
        "fleet",
        "period",
        "sessions",
        "sessions_by_transport",
        "tls_sessions",
        "total_bytes",
        "total_devices",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageSessionsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tls_sessions (nullable) is None
        # and model_fields_set contains the field
        if self.tls_sessions is None and "tls_sessions" in self.model_fields_set:
            _dict["tls_sessions"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageSessionsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "device": obj.get("device"),
                "first_sync_sessions": obj.get("first_sync_sessions"),
                "fleet": obj.get("fleet"),
                "period": obj.get("period"),
                "sessions": obj.get("sessions"),
                "sessions_by_transport": obj.get("sessions_by_transport"),
                "tls_sessions": obj.get("tls_sessions"),
                "total_bytes": obj.get("total_bytes"),
                "total_devices": obj.get("total_devices"),
            }
        )
        return _obj
