name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/notehub-py
    permissions:
      id-token: write 
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/auto-changelog
      # require commit format are "type(category): description [flag]"
    - name: Generate release changelog
      uses: ardalanamini/auto-changelog@v4
      id: changelog

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        python3 -m pip install --upgrade build
        python3 -m build
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./src/dist/
        repository-url: https://test.pypi.org/legacy/
